export const types = {
    ADD_HISTORY_QUERY: 'ADD_HISTORY_QUERY',
    SET_ROLES: 'SET_ROLES',
    SET_USERINFO: 'SET_USERINFO',
    SET_CONFIG: 'SET_CONFIG',
    SET_TOKEN: 'SET_TOKEN',
    LOGOUT: 'LOGOUT',
    // layout module
    COLLAPSE_LEFT: 'COLLAPSE_LEFT',
    COLLAPSE_RIGHT: 'COLLAPSE_RIGHT',
    SET_NOT_READ_MESSAGES: 'SET_NOT_READ_MESSAGES',
}
export default {}
